4 module is ready
js-tasks-ru/jsbasic-20221114_aleksey-titekin pull request #5
Opened 2022-12-04 08:29 UTC by AlekseyTitekin

2022-12-04 08:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-05 11:40 UTC, SinimaWath requested changes

2022-12-05 11:40 UTC, SinimaWath commented on 4-module/2-task/index.js
> +    row.cells[i++].style.backgroundColor = 'red';
Очень неявная запись: `[i++]`. Здесь намного прозе использовать цикл как снизу в комментариях.
Если нужна индексация, то не стоит использовать `for(let row of table.rows)`, а обычный for

2022-12-05 11:40 UTC, SinimaWath commented on 4-module/3-task/index.js
> +        row.cells[3].getAttribute("data-available") === "true"
Это data аттрибут, поэтому: `row.cells[3].dataset.available `

2022-12-05 12:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-07 17:18 UTC, SinimaWath approved these changes

2022-12-07 17:18 UTC, merged