5 module completed
js-tasks-ru/jsbasic-20221114_aleksey-titekin pull request #6
Opened 2022-12-10 22:20 UTC by AlekseyTitekin

2022-12-10 22:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-11 11:34 UTC, SinimaWath requested changes

2022-12-11 11:34 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  carousel.style.transform = `translateX(${step_offset*size_offset}px)`;
этот код повторяется 2 раза: в clickRight и clickLeft, давай переиспользуем

2022-12-11 11:34 UTC, SinimaWath commented on 5-module/3-task/index.js
> +let size_offset;
Непонятно зачем их делать глобальными

2022-12-11 15:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-11 16:04 UTC, SinimaWath approved these changes

2022-12-11 16:04 UTC, merged